[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31.1", default-features = false, features = ["default_fonts", "glow", "persistence"] }
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"

[lib]
crate-type = ["lib"]
